### ISSUE TITLE
Error when reading data in the Acclaim format

### ISSUE THREAD

**Issue by hyren** [lawrennd/mocap#6]
When the acclaimReadSkel is called, there is always an error.

Error using getline (line 77)
First argument is not a valid handle.

Error in acclaimReadSkel (line 23)
lin = getline(fid);

I am using the CMU motion database. The fid is 4, which means the file is opened correctly. Is there any method to avoid that? Thank you very much.

**Comment by chaneyddtt** [comment]
I also have the same problem,,do you figure it out? @hyren
